### ISSUE TITLE
Not showing on Staging Env

### ISSUE THREAD

**Issue by iva-fullers** [tobias-forkel/Magento2_NewsletterSubscribeAtCheckout#3]
Hi, we are having 4 envs, local, INT, STG and PROD.
Your module is showing on local and INT, but I cannot see it on STA. I can see it in admin, I enabled it, all good, but on a frontend - nothing. No errors and don't have any ideas left.

Any suggestions?

**Comment by tobias-forkel** [comment]
@iva-fullers 

MySQL into your database on STA and check if the field **newsletter_subscribe** is available on the quote table.

`DESCRIBE quote;`

If not remove the module from the table setup_module to run the install schema again.

`DELETE FROM setup_module WHERE module = 'Forkel_NewsletterSubscribeAtCheckout';`

I would also check the table **core_config_data** if there is any difference to your local environment.

`SELECT * FROM core_config_data WHERE path like '%forkel%';`

Let me know how it goes.

**Comment by iva-fullers** [comment]
Thank you for a quick response. I will try this and let you know how it went.

**Comment by iva-fullers** [comment]
All checked. Newsletter is part of a quote table and in core_config_data I have this:

```
1335    default    0    checkout/forkel_newslettersubscribeatcheckout/enabled    1
1336    default    0    checkout/forkel_newslettersubscribeatcheckout/checked    0
1337    default    0    checkout/forkel_newslettersubscribeatcheckout/label    Subscribe for a Newsletter1111
1338    default    0    checkout/forkel_newslettersubscribeatcheckout/note_enabled    1
1339    default    0    checkout/forkel_newslettersubscribeatcheckout/note    Some text
1374    default    0    advanced/modules_disable_output/Forkel_NewsletterSubscribeAtCheckout    0
```
On my local, last row was missing, I added the same and still was working on my local. 
I think that is installed fine but something is preventing loading of that block. In your html template you are checking if it is enabled but is checking this value:
```
checkout/forkel_newslettersubscribeatcheckout/enabled    1
```
Something is preventing it but cannot figure out what.
Thank you.

**Comment by tobias-forkel** [comment]
@iva-fullers 

Please replace ./app/code/Forkel/NewsletterSubscribeAtCheckout/etc/module.xml with the code below.

```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
<module name="Forkel_NewsletterSubscribeAtCheckout" setup_version="1.0.0">
    <sequence>
        <module name="Magento_Customer"/>
        <module name="Magento_Checkout"/>
        <module name="Magento_Sales"/>
        <module name="Magento_Quote"/>
        <module name="Magento_Payment"/>
        <module name="Magento_Vault"/>
        <module name="Magento_Store"/>
        <module name="Magento_Backend"/>
        <module name="Magento_Theme"/>
        <module name="Magento_Ui"/>
    </sequence>
</module>
</config>
```

If it doesn't work, can you please have a look if any other custom module is installed with the sequences below.

```
    <sequence>
        <module name="Magento_Checkout"/>
        <module name="Magento_Newsletter"/>
    </sequence>
```

Possible that something is wrong with the module load order.

**Comment by iva-fullers** [comment]
FIXED!!! It was exactly that. 
```
Forkel_NewsletterSubscribeAtCheckout 1
```
This was missing from config.php file. All sorted now. Thank you.

NOTE: Error was not due to anything wrong with this module's code it was our deployment process that taking config.php.template file and making it to config.php. So in this case module was missing from config.php.template file.  On a local env everything was working out of the box. Great module and great and fast support. Thank you.

**Comment by tobias-forkel** [comment]
Great to hear! I'll close the issue then.
