### ISSUE TITLE
Checkout Success

### ISSUE THREAD

**Issue by inelukipg** [tobias-forkel/Magento2_NewsletterSubscribeAtCheckout#5]
Hi,
Is it possible to add the newsletter subscribe on checkout success page instead?

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

It won't be possible with Magento2_NewsletterSubscribeAtCheckout but there are different ways to implement your requirement.

I am happy to custom build you something on top of my module, but I can't do it for free.

Cheers
