### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by ultrazeus** [tobias-forkel/Magento2_NewsletterSubscribeAtCheckout#6]
/var/www/domain.com/dev$ composer require "tobias-forkel/magento2-newsletter-subscribe-at-checkout":"1.0.3"

  [InvalidArgumentException]                                                                                  
  Could not find package tobias-forkel/magento2-newsletter-subscribe-at-checkout in a version matching 1.0.3  

Any ideas?

**Comment by tobias-forkel** [comment]
Hi @julienvb 

Please pull version 1.0.0 from https://github.com/magenizr/Magenizr_NewsletterSubscribeAtCheckout which is exactly the same code. It's just a different module name. I will continue with the module support there.

1. Remove the old module
```
composer remove tobias-forkel/magento2-newsletter-subscribe-at-checkout --no-update
```
2. Follow the composer install instructions on https://github.com/magenizr/Magenizr_NewsletterSubscribeAtCheckout

If you have any questions, please open a new issue there.
